name: project_4
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
    sdk: '>=2.19.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons:
    firebase_core:
    firebase_auth:
    cloud_firestore:

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints:

flutter:
    uses-material-design: true

    # assets:
    #   - images/a_dot_burr.jpeg
